### ISSUE TITLE
Allow Monolog 2.x

### ISSUE THREAD

**Issue by mimmi20** [llaville/monolog-callbackfilterhandler#5]
This Handler does not work with Monolog 2+.

**Comment by llaville** [comment]
Will release a new version monolog v2 compatible this week

**Comment by llaville** [comment]
@mimmi20 Branch `monolog-2` is available. I'll appreciate your feedbacks before I publish the new major version 2.0.0 tomorrow.

**Comment by llaville** [comment]
@weirdan I've changed CI (GA Workflow) and propose here a new major version. I'll greatly appreciated, if you can reviews it !

**Comment by llaville** [comment]
New major version 2.0.0 has just been released
